name: Release go-test

on:
  push:
    tags:
      - 'v*'
      - 'draft-*'

jobs:
  publishGitRelease:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
          check-latest: true

      #rhash 用来生成 checksums 软件哈希信息，gox 用来将代码编译为不同架构目标。./scripts/xcompile.sh 是具体的编译脚本,需要放到仓库根目录的scripts下。
      - name: Cross compile
        run: |
          sudo apt-get install rhash -y
          go install github.com/mitchellh/gox@v1.0.1
          mkdir -p build
          ./scripts/xcompile.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:  build/*
          draft: true
          fail_on_unmatched_files: true
